// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEKdlCvGw8WfDa2_qp4qewOSO1ap8Y52k',
    appId: '1:71607721952:web:56643ed05b137af10ed585',
    messagingSenderId: '71607721952',
    projectId: 'continent-9b9dd',
    authDomain: 'continent-9b9dd.firebaseapp.com',
    storageBucket: 'continent-9b9dd.appspot.com',
    measurementId: 'G-HV619XMCT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOwxsQze0mSzMetMvwq8hHgOfUH1BZNAM',
    appId: '1:71607721952:android:fa8f09c59a018b460ed585',
    messagingSenderId: '71607721952',
    projectId: 'continent-9b9dd',
    storageBucket: 'continent-9b9dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXTGNeF25g04IwLLqaXxIjWUrT8hA68gA',
    appId: '1:71607721952:ios:14042be147c496e60ed585',
    messagingSenderId: '71607721952',
    projectId: 'continent-9b9dd',
    storageBucket: 'continent-9b9dd.appspot.com',
    iosBundleId: 'com.example.continentsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXTGNeF25g04IwLLqaXxIjWUrT8hA68gA',
    appId: '1:71607721952:ios:e79b185378b71eb20ed585',
    messagingSenderId: '71607721952',
    projectId: 'continent-9b9dd',
    storageBucket: 'continent-9b9dd.appspot.com',
    iosBundleId: 'com.example.continentsApp.RunnerTests',
  );
}
